# Generated by Django 5.1.2 on 2025-04-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0004_appointment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.JSONField(default=list),
        ),
    ]
